version: "3.8"
services:
  project:
    build: .
    volumes:
      - .:/django
    image: project:latest
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    
  nginx:
    build: ./nginx
    ports:
      - 80:80
    image: nginx:latest
    depends_on:
      - project